apiVersion: v1
kind: Service
metadata:
  name:      {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{ include "statuslistservice.selectorLabels" . }}
  ports:
    - port: 8080
      protocol: TCP