openapi: 3.0.3
info:
    title: XFSC Status List Service
    description: Status list REST API
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /health:
        get:
            tags:
                - status
            summary: health status
            operationId: status#health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Dolorem ipsa voluptates.
                            example: Omnis iure et aut officia sit non.
    /status/{tenantId}/{listId}:
        get:
            tags:
                - status
            summary: getList status
            description: Returns a status list as JSON, JWT status list, or StatusList2021 credential depending on Content-Type.
            operationId: status#getList
            parameters:
                - name: tenantId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Nostrum et qui impedit.
                  example: Aliquid in non ut et magni.
                - name: listId
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 572773340723933313
                    format: int64
                  example: 5478086650043458636
                - name: Content-Type
                  in: header
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: Dolore commodi temporibus qui sunt.
                  example: Dolores et aspernatur perferendis quasi reiciendis.
                - name: Accept
                  in: header
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: Officia et repudiandae et molestiae labore.
                  example: Tempore ad voluptas nihil cumque corporis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: Nihil eos dolor consectetur itaque sunt soluta.
                            example: Temporibus ut.
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Soluta ut.
                                status: 4626048081921224596
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Qui est.
                                status: 2187445100556675094
    /status/{tenantId}/{listId}/revoke/{index}:
        post:
            tags:
                - status
            summary: revoke status
            description: Revokes a credential by setting the bit at the given index.
            operationId: status#revoke
            parameters:
                - name: tenantId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Ut et.
                  example: Vel sunt magni id voluptatum.
                - name: listId
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 5730539016118596574
                    format: int64
                  example: 3930967623290764634
                - name: index
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 9150845651761190495
                    format: int64
                  example: 3083699621273940174
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/XfscStatusListRevoke'
                            example:
                                index: 4071898898058540969
                                listId: 8241164471203716713
                                status: Laborum ipsum aliquid ex porro.
                                tenantId: Nesciunt illo necessitatibus esse et quas.
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Dolor veniam.
                                status: 5703605082360234551
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Voluptatem accusamus maiores.
                                status: 4489760366714551739
components:
    schemas:
        XfscError:
            type: object
            properties:
                message:
                    type: string
                    example: Voluptatem et.
                status:
                    type: integer
                    example: 5647168246699591304
                    format: int64
            example:
                message: Doloribus in veritatis qui sed est sunt.
                status: 8957644760419840764
            required:
                - message
                - status
        XfscStatusList:
            type: object
            properties:
                list:
                    type: string
                    example: Magnam quis.
                listId:
                    type: integer
                    example: 1069474788048321663
                    format: int64
                tenantId:
                    type: string
                    example: Sit natus provident.
            example:
                list: Et dolorem accusamus.
                listId: 4593095119214657981
                tenantId: Ex aut ratione.
            required:
                - tenantId
                - listId
                - list
        XfscStatusListRevoke:
            type: object
            properties:
                index:
                    type: integer
                    example: 7800793495709443590
                    format: int64
                listId:
                    type: integer
                    example: 1663174826580740662
                    format: int64
                status:
                    type: string
                    example: Quisquam aut aut a.
                tenantId:
                    type: string
                    example: Ut nobis incidunt delectus dolore.
            example:
                index: 5131945160491360143
                listId: 4268735045851758670
                status: Sed est magni excepturi pariatur.
                tenantId: Molestias non cupiditate rem dignissimos et.
            required:
                - tenantId
                - listId
                - index
                - status
tags:
    - name: status
      description: Status list endpoints
