openapi: 3.0.3
info:
    title: XFSC Status List Service
    description: Status list REST API
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /health:
        get:
            tags:
                - status
            summary: health status
            operationId: status#health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Eos dolor consectetur itaque sunt soluta.
                            example: Nostrum et qui impedit.
    /status/{tenantId}/{listId}/revoke/{index}:
        post:
            tags:
                - status
            summary: revoke status
            description: Revokes a credential by setting the bit at the given index.
            operationId: status#revoke
            parameters:
                - name: tenantId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Eligendi mollitia aut.
                  example: Nesciunt illo necessitatibus esse et quas.
                - name: listId
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 8241164471203716713
                    format: int64
                  example: 4071898898058540969
                - name: index
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 8132532975817278843
                    format: int64
                  example: 5789449076494185776
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/XfscStatusListRevoke'
                            example:
                                index: 8373912765981977176
                                listId: 4776042239491796006
                                status: Dolorem cupiditate maiores esse.
                                tenantId: Aliquid ex porro illo fugit.
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Minus quia perferendis iure qui.
                                status: 5448277403818738703
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/vnd.xfsc.error:
                            schema:
                                $ref: '#/components/schemas/XfscError'
                            example:
                                message: Veniam dicta non voluptatem.
                                status: 9113095539974995838
    /v1/tenants/{tenantId}/status/{listId}:
        get:
            tags:
                - status
            summary: getList status
            description: Returns a status list as JSON, JWT status list, or StatusList2021 credential depending on Content-Type.
            operationId: status#getList
            parameters:
                - name: tenantId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Aliquid in non ut et magni.
                  example: Sit eaque dolore commodi temporibus qui sunt.
                - name: listId
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 2706143008988716459
                    format: int64
                  example: 8009858722958566378
                - name: Accept
                  in: header
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: Aspernatur perferendis quasi reiciendis facilis officia.
                  example: Repudiandae et molestiae labore officiis tempore.
                - name: X-Group-Id
                  in: header
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: Voluptas nihil cumque corporis ratione temporibus ut.
                  example: Ut et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                example: Omnis iure et aut officia sit non.
                            example: Vel sunt magni id voluptatum.
components:
    schemas:
        XfscError:
            type: object
            properties:
                message:
                    type: string
                    example: Veritatis qui sed est sunt.
                status:
                    type: integer
                    example: 8957644760419840764
                    format: int64
            example:
                message: Dolorem ipsa voluptates.
                status: 1326464516481511563
            required:
                - message
                - status
        XfscStatusList:
            type: object
            properties:
                list:
                    type: string
                    example: Rem magnam quis vel ex aut ratione.
                listId:
                    type: integer
                    example: 5978219193760281404
                    format: int64
                tenantId:
                    type: string
                    example: Illo sit natus.
            example:
                list: Delectus dolore.
                listId: 8469546071820002919
                tenantId: Sit et dolorem accusamus nihil ut.
            required:
                - tenantId
                - listId
                - list
        XfscStatusListRevoke:
            type: object
            properties:
                index:
                    type: integer
                    example: 1175042874615874555
                    format: int64
                listId:
                    type: integer
                    example: 1312543848096475825
                    format: int64
                status:
                    type: string
                    example: Non cupiditate rem dignissimos et.
                tenantId:
                    type: string
                    example: Aut assumenda quisquam aut aut.
            example:
                index: 5042207198975027724
                listId: 6184804881049467816
                status: Saepe voluptatem et aspernatur necessitatibus doloribus.
                tenantId: Qui adipisci sed est.
            required:
                - tenantId
                - listId
                - index
                - status
tags:
    - name: status
      description: Status list endpoints
