name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    with: 
      dockerfile: "deployment/docker"
      harbor_config: "deployment/harbor.config"
  helm:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    with: 
      buildContext:  "deployment/helm"
      harbor_config: "deployment/harbor.config"